[package]
name = "win_events_dumper"
version = "0.1.0"
authors = ["Adam Lesperance <lespea@gmail.com>"]
edition = "2018"

[dependencies]
flate2 = "1"
slog = "2"
sloggers = "0"
snafu = "0.5"
#wchar = "0.5"
#widestring = "0.4"
win_events = { version = "0", path = "../win_events" }
