[package]
name = "wevents_dumper"
version = "0.1.0"
authors = ["Adam Lesperance <lespea@gmail.com>"]
edition = "2018"

[dependencies]
flate2 = "1"
slog = "2"
sloggers = "0"
snafu = "0.4"
#wchar = "0.5"
#widestring = "0.4"
wevents = { version = "0", path = "../wevents" }
